version: '3'

networks:
  my-network:
    driver: bridge

services:
  gpt-pilot:
    networks:
      - my-network
    environment:
      # Common
      MAX_TOKENS: 8192
      DATABASE_TYPE: postgres
      DB_NAME: pilot
      DB_HOST: postgres
      DB_PORT: 543
